/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SButton {
    }
    interface SInput {
        "placeholder": string;
        "value": string;
    }
}
declare global {
    interface HTMLSButtonElement extends Components.SButton, HTMLStencilElement {
    }
    var HTMLSButtonElement: {
        prototype: HTMLSButtonElement;
        new (): HTMLSButtonElement;
    };
    interface HTMLSInputElement extends Components.SInput, HTMLStencilElement {
    }
    var HTMLSInputElement: {
        prototype: HTMLSInputElement;
        new (): HTMLSInputElement;
    };
    interface HTMLElementTagNameMap {
        "s-button": HTMLSButtonElement;
        "s-input": HTMLSInputElement;
    }
}
declare namespace LocalJSX {
    interface SButton {
    }
    interface SInput {
        "onSChange"?: (event: CustomEvent<string>) => void;
        "onSInput"?: (event: CustomEvent<InputEvent>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "s-button": SButton;
        "s-input": SInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "s-button": LocalJSX.SButton & JSXBase.HTMLAttributes<HTMLSButtonElement>;
            "s-input": LocalJSX.SInput & JSXBase.HTMLAttributes<HTMLSInputElement>;
        }
    }
}
