/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { UIColor } from "./global/ui-color";
import { ButtonVariant } from "./components/vivid-button/vivid-button";
import { OverlayPosition } from "./components/vivid-overlay/vivid-overlay";
export namespace Components {
    interface VividBadge {
        "color": UIColor;
    }
    interface VividButton {
        "color": UIColor;
        "variant": ButtonVariant;
    }
    interface VividCard {
    }
    interface VividCollapse {
        "isHidden": boolean;
    }
    interface VividContainer {
    }
    interface VividDatepicker {
        "value": Date;
    }
    interface VividFlex {
        "baseFraction": number;
    }
    interface VividFlexItem {
        "lg": number | 'auto';
        "md": number | 'auto';
        "rowWidthChanged": (width: number) => Promise<void>;
        "sm": number | 'auto';
        "xl": number | 'auto';
        "xs": number | 'auto';
        "xxl": number | 'auto';
    }
    interface VividGrid {
        "columnGap": string;
        "columns": string;
        "rowGap": string;
        "rows": string;
    }
    interface VividGridItem {
        "column": number;
        "columnSpan": number;
        "row": number;
        "rowSpan": number;
    }
    interface VividInput {
        "placeholder": string;
        "value": string;
    }
    interface VividOverlay {
        "minimizedScale": string;
        "position": OverlayPosition | string;
        "showed": boolean;
        "transformOrigin": string;
        "useBackdrop": boolean;
        "zIndex": number;
    }
    interface VividProvider {
    }
    interface VividRange {
        "max": number;
        "min": number;
        "step": number | '' | 'any';
        "value": number;
    }
    interface VividRatioBox {
        "heightRatio": number;
        "widthRatio": number;
    }
    interface VividSelect {
        "color": UIColor;
        "placeholder": string;
        "value": string;
    }
    interface VividSelectOption {
        "highlightColor": string;
        "isSelected": boolean;
        "parentSelectElement": HTMLVividSelectElement;
        "value": string;
    }
    interface VividToggle {
        "checked": boolean;
        "color": UIColor;
        "scale": number;
    }
}
declare global {
    interface HTMLVividBadgeElement extends Components.VividBadge, HTMLStencilElement {
    }
    var HTMLVividBadgeElement: {
        prototype: HTMLVividBadgeElement;
        new (): HTMLVividBadgeElement;
    };
    interface HTMLVividButtonElement extends Components.VividButton, HTMLStencilElement {
    }
    var HTMLVividButtonElement: {
        prototype: HTMLVividButtonElement;
        new (): HTMLVividButtonElement;
    };
    interface HTMLVividCardElement extends Components.VividCard, HTMLStencilElement {
    }
    var HTMLVividCardElement: {
        prototype: HTMLVividCardElement;
        new (): HTMLVividCardElement;
    };
    interface HTMLVividCollapseElement extends Components.VividCollapse, HTMLStencilElement {
    }
    var HTMLVividCollapseElement: {
        prototype: HTMLVividCollapseElement;
        new (): HTMLVividCollapseElement;
    };
    interface HTMLVividContainerElement extends Components.VividContainer, HTMLStencilElement {
    }
    var HTMLVividContainerElement: {
        prototype: HTMLVividContainerElement;
        new (): HTMLVividContainerElement;
    };
    interface HTMLVividDatepickerElement extends Components.VividDatepicker, HTMLStencilElement {
    }
    var HTMLVividDatepickerElement: {
        prototype: HTMLVividDatepickerElement;
        new (): HTMLVividDatepickerElement;
    };
    interface HTMLVividFlexElement extends Components.VividFlex, HTMLStencilElement {
    }
    var HTMLVividFlexElement: {
        prototype: HTMLVividFlexElement;
        new (): HTMLVividFlexElement;
    };
    interface HTMLVividFlexItemElement extends Components.VividFlexItem, HTMLStencilElement {
    }
    var HTMLVividFlexItemElement: {
        prototype: HTMLVividFlexItemElement;
        new (): HTMLVividFlexItemElement;
    };
    interface HTMLVividGridElement extends Components.VividGrid, HTMLStencilElement {
    }
    var HTMLVividGridElement: {
        prototype: HTMLVividGridElement;
        new (): HTMLVividGridElement;
    };
    interface HTMLVividGridItemElement extends Components.VividGridItem, HTMLStencilElement {
    }
    var HTMLVividGridItemElement: {
        prototype: HTMLVividGridItemElement;
        new (): HTMLVividGridItemElement;
    };
    interface HTMLVividInputElement extends Components.VividInput, HTMLStencilElement {
    }
    var HTMLVividInputElement: {
        prototype: HTMLVividInputElement;
        new (): HTMLVividInputElement;
    };
    interface HTMLVividOverlayElement extends Components.VividOverlay, HTMLStencilElement {
    }
    var HTMLVividOverlayElement: {
        prototype: HTMLVividOverlayElement;
        new (): HTMLVividOverlayElement;
    };
    interface HTMLVividProviderElement extends Components.VividProvider, HTMLStencilElement {
    }
    var HTMLVividProviderElement: {
        prototype: HTMLVividProviderElement;
        new (): HTMLVividProviderElement;
    };
    interface HTMLVividRangeElement extends Components.VividRange, HTMLStencilElement {
    }
    var HTMLVividRangeElement: {
        prototype: HTMLVividRangeElement;
        new (): HTMLVividRangeElement;
    };
    interface HTMLVividRatioBoxElement extends Components.VividRatioBox, HTMLStencilElement {
    }
    var HTMLVividRatioBoxElement: {
        prototype: HTMLVividRatioBoxElement;
        new (): HTMLVividRatioBoxElement;
    };
    interface HTMLVividSelectElement extends Components.VividSelect, HTMLStencilElement {
    }
    var HTMLVividSelectElement: {
        prototype: HTMLVividSelectElement;
        new (): HTMLVividSelectElement;
    };
    interface HTMLVividSelectOptionElement extends Components.VividSelectOption, HTMLStencilElement {
    }
    var HTMLVividSelectOptionElement: {
        prototype: HTMLVividSelectOptionElement;
        new (): HTMLVividSelectOptionElement;
    };
    interface HTMLVividToggleElement extends Components.VividToggle, HTMLStencilElement {
    }
    var HTMLVividToggleElement: {
        prototype: HTMLVividToggleElement;
        new (): HTMLVividToggleElement;
    };
    interface HTMLElementTagNameMap {
        "vivid-badge": HTMLVividBadgeElement;
        "vivid-button": HTMLVividButtonElement;
        "vivid-card": HTMLVividCardElement;
        "vivid-collapse": HTMLVividCollapseElement;
        "vivid-container": HTMLVividContainerElement;
        "vivid-datepicker": HTMLVividDatepickerElement;
        "vivid-flex": HTMLVividFlexElement;
        "vivid-flex-item": HTMLVividFlexItemElement;
        "vivid-grid": HTMLVividGridElement;
        "vivid-grid-item": HTMLVividGridItemElement;
        "vivid-input": HTMLVividInputElement;
        "vivid-overlay": HTMLVividOverlayElement;
        "vivid-provider": HTMLVividProviderElement;
        "vivid-range": HTMLVividRangeElement;
        "vivid-ratio-box": HTMLVividRatioBoxElement;
        "vivid-select": HTMLVividSelectElement;
        "vivid-select-option": HTMLVividSelectOptionElement;
        "vivid-toggle": HTMLVividToggleElement;
    }
}
declare namespace LocalJSX {
    interface VividBadge {
        "color"?: UIColor;
    }
    interface VividButton {
        "color"?: UIColor;
        "variant"?: ButtonVariant;
    }
    interface VividCard {
    }
    interface VividCollapse {
        "isHidden"?: boolean;
    }
    interface VividContainer {
    }
    interface VividDatepicker {
        "value"?: Date;
    }
    interface VividFlex {
        "baseFraction"?: number;
    }
    interface VividFlexItem {
        "lg"?: number | 'auto';
        "md"?: number | 'auto';
        "sm"?: number | 'auto';
        "xl"?: number | 'auto';
        "xs"?: number | 'auto';
        "xxl"?: number | 'auto';
    }
    interface VividGrid {
        "columnGap"?: string;
        "columns"?: string;
        "rowGap"?: string;
        "rows"?: string;
    }
    interface VividGridItem {
        "column"?: number;
        "columnSpan"?: number;
        "row"?: number;
        "rowSpan"?: number;
    }
    interface VividInput {
        "onSChange"?: (event: CustomEvent<string>) => void;
        "onSInput"?: (event: CustomEvent<InputEvent>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface VividOverlay {
        "minimizedScale"?: string;
        "position"?: OverlayPosition | string;
        "showed"?: boolean;
        "transformOrigin"?: string;
        "useBackdrop"?: boolean;
        "zIndex"?: number;
    }
    interface VividProvider {
    }
    interface VividRange {
        "max"?: number;
        "min"?: number;
        "onSChange"?: (event: CustomEvent<string>) => void;
        "onSInput"?: (event: CustomEvent<InputEvent>) => void;
        "step"?: number | '' | 'any';
        "value"?: number;
    }
    interface VividRatioBox {
        "heightRatio"?: number;
        "widthRatio"?: number;
    }
    interface VividSelect {
        "color"?: UIColor;
        "onSChange"?: (event: CustomEvent<string>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface VividSelectOption {
        "highlightColor"?: string;
        "isSelected"?: boolean;
        "parentSelectElement"?: HTMLVividSelectElement;
        "value"?: string;
    }
    interface VividToggle {
        "checked"?: boolean;
        "color"?: UIColor;
        "onSChange"?: (event: CustomEvent<boolean>) => void;
        "scale"?: number;
    }
    interface IntrinsicElements {
        "vivid-badge": VividBadge;
        "vivid-button": VividButton;
        "vivid-card": VividCard;
        "vivid-collapse": VividCollapse;
        "vivid-container": VividContainer;
        "vivid-datepicker": VividDatepicker;
        "vivid-flex": VividFlex;
        "vivid-flex-item": VividFlexItem;
        "vivid-grid": VividGrid;
        "vivid-grid-item": VividGridItem;
        "vivid-input": VividInput;
        "vivid-overlay": VividOverlay;
        "vivid-provider": VividProvider;
        "vivid-range": VividRange;
        "vivid-ratio-box": VividRatioBox;
        "vivid-select": VividSelect;
        "vivid-select-option": VividSelectOption;
        "vivid-toggle": VividToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vivid-badge": LocalJSX.VividBadge & JSXBase.HTMLAttributes<HTMLVividBadgeElement>;
            "vivid-button": LocalJSX.VividButton & JSXBase.HTMLAttributes<HTMLVividButtonElement>;
            "vivid-card": LocalJSX.VividCard & JSXBase.HTMLAttributes<HTMLVividCardElement>;
            "vivid-collapse": LocalJSX.VividCollapse & JSXBase.HTMLAttributes<HTMLVividCollapseElement>;
            "vivid-container": LocalJSX.VividContainer & JSXBase.HTMLAttributes<HTMLVividContainerElement>;
            "vivid-datepicker": LocalJSX.VividDatepicker & JSXBase.HTMLAttributes<HTMLVividDatepickerElement>;
            "vivid-flex": LocalJSX.VividFlex & JSXBase.HTMLAttributes<HTMLVividFlexElement>;
            "vivid-flex-item": LocalJSX.VividFlexItem & JSXBase.HTMLAttributes<HTMLVividFlexItemElement>;
            "vivid-grid": LocalJSX.VividGrid & JSXBase.HTMLAttributes<HTMLVividGridElement>;
            "vivid-grid-item": LocalJSX.VividGridItem & JSXBase.HTMLAttributes<HTMLVividGridItemElement>;
            "vivid-input": LocalJSX.VividInput & JSXBase.HTMLAttributes<HTMLVividInputElement>;
            "vivid-overlay": LocalJSX.VividOverlay & JSXBase.HTMLAttributes<HTMLVividOverlayElement>;
            "vivid-provider": LocalJSX.VividProvider & JSXBase.HTMLAttributes<HTMLVividProviderElement>;
            "vivid-range": LocalJSX.VividRange & JSXBase.HTMLAttributes<HTMLVividRangeElement>;
            "vivid-ratio-box": LocalJSX.VividRatioBox & JSXBase.HTMLAttributes<HTMLVividRatioBoxElement>;
            "vivid-select": LocalJSX.VividSelect & JSXBase.HTMLAttributes<HTMLVividSelectElement>;
            "vivid-select-option": LocalJSX.VividSelectOption & JSXBase.HTMLAttributes<HTMLVividSelectOptionElement>;
            "vivid-toggle": LocalJSX.VividToggle & JSXBase.HTMLAttributes<HTMLVividToggleElement>;
        }
    }
}
